DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    hash TEXT NOT NULL,
    username TEXT NOT NULL
);

CREATE UNIQUE INDEX username ON users (username);
